package com.fangxu.dota2helper.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GREEN_NEWS".
 */
public class GreenNews {

    private Long id;
    private String newslistjson;

    public GreenNews() {
    }

    public GreenNews(Long id) {
        this.id = id;
    }

    public GreenNews(Long id, String newslistjson) {
        this.id = id;
        this.newslistjson = newslistjson;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNewslistjson() {
        return newslistjson;
    }

    public void setNewslistjson(String newslistjson) {
        this.newslistjson = newslistjson;
    }

}
