package com.fangxu.dota2helper.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GREEN_UPDATE".
 */
public class GreenUpdate {

    private Long id;
    private String updatelistjson;

    public GreenUpdate() {
    }

    public GreenUpdate(Long id) {
        this.id = id;
    }

    public GreenUpdate(Long id, String updatelistjson) {
        this.id = id;
        this.updatelistjson = updatelistjson;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUpdatelistjson() {
        return updatelistjson;
    }

    public void setUpdatelistjson(String updatelistjson) {
        this.updatelistjson = updatelistjson;
    }

}
