package com.fangxu.dota2helper.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GREEN_WATCHED_VIDEO".
 */
public class GreenWatchedVideo {

    private String videoyoukuvid;
    private String videobackground;
    private String videotitle;
    private Long videowatchtime;
    private Integer videoduration;
    private Integer videoplaytime;
    private Boolean videoEnded;

    public GreenWatchedVideo() {
    }

    public GreenWatchedVideo(String videoyoukuvid) {
        this.videoyoukuvid = videoyoukuvid;
    }

    public GreenWatchedVideo(String videoyoukuvid, String videobackground, String videotitle, Long videowatchtime, Integer videoduration, Integer videoplaytime, Boolean videoEnded) {
        this.videoyoukuvid = videoyoukuvid;
        this.videobackground = videobackground;
        this.videotitle = videotitle;
        this.videowatchtime = videowatchtime;
        this.videoduration = videoduration;
        this.videoplaytime = videoplaytime;
        this.videoEnded = videoEnded;
    }

    public String getVideoyoukuvid() {
        return videoyoukuvid;
    }

    public void setVideoyoukuvid(String videoyoukuvid) {
        this.videoyoukuvid = videoyoukuvid;
    }

    public String getVideobackground() {
        return videobackground;
    }

    public void setVideobackground(String videobackground) {
        this.videobackground = videobackground;
    }

    public String getVideotitle() {
        return videotitle;
    }

    public void setVideotitle(String videotitle) {
        this.videotitle = videotitle;
    }

    public Long getVideowatchtime() {
        return videowatchtime;
    }

    public void setVideowatchtime(Long videowatchtime) {
        this.videowatchtime = videowatchtime;
    }

    public Integer getVideoduration() {
        return videoduration;
    }

    public void setVideoduration(Integer videoduration) {
        this.videoduration = videoduration;
    }

    public Integer getVideoplaytime() {
        return videoplaytime;
    }

    public void setVideoplaytime(Integer videoplaytime) {
        this.videoplaytime = videoplaytime;
    }

    public Boolean getVideoEnded() {
        return videoEnded;
    }

    public void setVideoEnded(Boolean videoEnded) {
        this.videoEnded = videoEnded;
    }

}
