package com.fangxu.dota2helper.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.fangxu.dota2helper.greendao.GreenStrategy;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GREEN_STRATEGY".
*/
public class GreenStrategyDao extends AbstractDao<GreenStrategy, Long> {

    public static final String TABLENAME = "GREEN_STRATEGY";

    /**
     * Properties of entity GreenStrategy.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Strategylistjson = new Property(1, String.class, "strategylistjson", false, "STRATEGYLISTJSON");
        public final static Property Strategytype = new Property(2, String.class, "strategytype", false, "STRATEGYTYPE");
    };


    public GreenStrategyDao(DaoConfig config) {
        super(config);
    }
    
    public GreenStrategyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GREEN_STRATEGY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"STRATEGYLISTJSON\" TEXT," + // 1: strategylistjson
                "\"STRATEGYTYPE\" TEXT);"); // 2: strategytype
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GREEN_STRATEGY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GreenStrategy entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String strategylistjson = entity.getStrategylistjson();
        if (strategylistjson != null) {
            stmt.bindString(2, strategylistjson);
        }
 
        String strategytype = entity.getStrategytype();
        if (strategytype != null) {
            stmt.bindString(3, strategytype);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public GreenStrategy readEntity(Cursor cursor, int offset) {
        GreenStrategy entity = new GreenStrategy( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // strategylistjson
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // strategytype
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GreenStrategy entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStrategylistjson(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setStrategytype(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(GreenStrategy entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(GreenStrategy entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
