package com.fangxu.dota2helper.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GREEN_STRATEGY".
 */
public class GreenStrategy {

    private Long id;
    private String strategylistjson;
    private String strategytype;

    public GreenStrategy() {
    }

    public GreenStrategy(Long id) {
        this.id = id;
    }

    public GreenStrategy(Long id, String strategylistjson, String strategytype) {
        this.id = id;
        this.strategylistjson = strategylistjson;
        this.strategytype = strategytype;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getStrategylistjson() {
        return strategylistjson;
    }

    public void setStrategylistjson(String strategylistjson) {
        this.strategylistjson = strategylistjson;
    }

    public String getStrategytype() {
        return strategytype;
    }

    public void setStrategytype(String strategytype) {
        this.strategytype = strategytype;
    }

}
